### ISSUE TITLE
cuda runtime error (30) :

### ISSUE THREAD

**Issue by mpicci** [mingyuliutw/CoGAN_PyTorch#1]
Hi,
which PyTorch version are you using?
I get this error

Let the journey begin!
<net_config.NetConfig object at 0x7f3e62ff3d50>
(30000, 28, 28, 1)
(30000, 28, 28, 1)
THCudaCheck FAIL file=/py/conda-bld/pytorch_1493676237139/work/torch/lib/THC/THCGeneral.c line=66 error=30 : unknown error
Traceback (most recent call last):
  File "train_cogan_mnistedge.py", line 78, in <module>
    main(sys.argv)
  File "train_cogan_mnistedge.py", line 44, in main
    trainer.cuda()
  File "/home/piccir/Documents/Repository/CoGAN_PyTorch/src/trainer_cogan_mnistedge.py", line 22, in cuda
    self.dis.cuda()
  File "/home/piccir/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 147, in cuda
    return self._apply(lambda t: t.cuda(device_id))
  File "/home/piccir/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 118, in _apply
    module._apply(fn)
  File "/home/piccir/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 124, in _apply
    param.data = fn(param.data)
  File "/home/piccir/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 147, in <lambda>
    return self._apply(lambda t: t.cuda(device_id))
  File "/home/piccir/anaconda2/lib/python2.7/site-packages/torch/_utils.py", line 65, in _cuda
    return new_type(self.size()).copy_(self, async)
  File "/home/piccir/anaconda2/lib/python2.7/site-packages/torch/cuda/__init__.py", line 272, in __new__
    _lazy_init()
  File "/home/piccir/anaconda2/lib/python2.7/site-packages/torch/cuda/__init__.py", line 85, in _lazy_init
    torch._C._cuda_init()
RuntimeError: cuda runtime error (30) : unknown error at /py/conda-bld/pytorch_1493676237139/work/torch/lib/THC/THCGeneral.c:66

**Comment by mingyuliutw** [comment]
Based on the error messages, the problem is the data shape. In your PyTorch version, the data shape is 
(30000, 28, 28, 1)
You need to transform them to make it looks like
(30000, 1, 28, 28)
